version: 4
homeassistant:
  enabled: true
advanced:
  network_key:
    - 67
    - 212
    - 47
    - 241
    - 144
    - 81
    - 76
    - 68
    - 144
    - 190
    - 154
    - 199
    - 158
    - 167
    - 127
    - 31
  pan_id: 46278
  ext_pan_id:
    - 78
    - 169
    - 78
    - 247
    - 118
    - 8
    - 216
    - 95
  log_level: info
mqtt:
  server: mqtt://core-mosquitto
  user: mqtt-user
  password: S81tren0!
serial:
  port: /dev/ttyUSB0
frontend:
  enabled: true
  port: 8099
devices:
  '0xa4c1383ffdd376bc':
    friendly_name: Radiatore_bagno_nero
    description: Termostato Bagno Nero
  '0xa4c13822e9318541':
    friendly_name: Presa_lavastoviglie
  '0xa4c13884357b1a7b':
    friendly_name: Presa_lavatrice
  '0xa4c138e3d6c1e19d':
    friendly_name: Radiatore_cameretta
  '0xa4c13867cc34647a':
    friendly_name: Rediatore_ingresso
  '0xa4c1387e8d5d9d7c':
    friendly_name: Radiatore_cucina
  '0xa4c1381fc6dea485':
    friendly_name: Radiatore_camera
  '0xa4c1385d95724ec1':
    friendly_name: Radiatore_bagno_rosso
  '0xa4c1383c9974f2ed':
    friendly_name: Termometro_living
    temperature_precision: 3
  '0xa4c138faa331d764':
    friendly_name: Press_bagno_nero
  '0xa4c1381a73981eff':
    friendly_name: Termometro_outdoor
    temperature_precision: 3
    temperature_calibration: -3
    humidity_calibration: ''
groups:
  '1':
    friendly_name: Radiatori
